/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.dtac.inventory.action;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.LookupDispatchAction;

import com.dtac.admin.data.DBMasterTable;
import com.dtac.inventory.data.DBMaterial;
import com.dtac.inventory.data.DBMaterialType;
import com.dtac.inventory.form.MaterialForm;


/**
 * MyEclipse Struts 
 * Creation date: 12-06-2012
 */
public class ItemnoSearchAction extends LookupDispatchAction {

	protected Map getKeyMethodMap() {
		Map map = new HashMap();
		map.put("materialform.button.search", 	"search");
		return map;
	}

	public ActionForward search(ActionMapping mapping, ActionForm form,
		HttpServletRequest request, HttpServletResponse response)
	throws Exception { //12-06-2012
		String forwardText 	= "success";
		String loginId 		= "";
		//String appCode 		= "pu11";
		try {
			HttpSession session = request.getSession();
			if (session.isNew()) {
				session.invalidate();
				request.setAttribute("alertMessage", "Session Timeout. Login again.");
				return mapping.findForward("relogin");
			} else {
				loginId = (String) session.getAttribute("loginId");
				if (loginId == null) {
					request.setAttribute("alertMessage", "Please Login.");
					return mapping.findForward("relogin");
				}
			}
			
			// 23/05/2013
			MaterialForm materialForm = (MaterialForm) form;			
			String matCode		= materialForm.getMatCode();
			//String matName		= new String(materialForm.getMatName().getBytes("ISO8859_1"),"utf-8");
			//String matSearchName= new String(materialForm.getMatSearchName().getBytes("ISO8859_1"),"utf-8");
			String matTypeCode	= materialForm.getMatTypeCode();
			String matGrpCode	= materialForm.getMatGrpCode(); if (matGrpCode == null) matGrpCode = "";
			String matColorCode = materialForm.getMatColorCode();
			String matStuffCode	= materialForm.getMatStuffCode();
			String refMatCode	= materialForm.getRefMatCode();
			String matStatus	= materialForm.getMatStatus();
			String pUnit		= materialForm.getpUnit();
			String matBrandCode	= materialForm.getMatBrandCode();
			
			DBMaterialType dbMaterialType = new DBMaterialType();
			List matTypeList = dbMaterialType.GetMaterialTypeList("");
			if (matTypeList.size() > 0) request.setAttribute("matTypeList", matTypeList);

			List matGrpList = dbMaterialType.GetMaterialGrpList(matTypeCode, "", "AC");
			if (matGrpList.size() > 0 && !matTypeCode.equals("")) request.setAttribute("matGrpList", matGrpList);
			
			DBMaterial dbMaterial = new DBMaterial();
			List materialList = dbMaterial.GetMaterialList(matCode, "", "","", matTypeCode, matGrpCode, 
				matColorCode, matStuffCode, refMatCode, matStatus, pUnit, matBrandCode);
			if (materialList.size() > 0) request.setAttribute("materialList", materialList);

			DBMasterTable dbMasterTable = new DBMasterTable();
			List colorList = dbMasterTable.GetMasterTableDTList("colo", "", "", "AC");
			if (colorList.size() > 0) request.setAttribute("colorList", colorList);
			
			List unitList = dbMasterTable.GetMasterTableDTList("unit", "", "", "AC");
			if (unitList.size() > 0) request.setAttribute("unitList", unitList);
			
			List brandList = dbMasterTable.GetMasterTableDTList("bran", "", "", "AC");
			if (brandList.size() > 0) request.setAttribute("brandList", brandList);

			List stuffList = dbMasterTable.GetMasterTableDTList("stuf", "", "", "AC");
			if (stuffList.size() > 0) request.setAttribute("stuffList", stuffList);
			
			List sizeList = dbMasterTable.GetMasterTableDTList("size", "", "", "AC");
			if (sizeList.size() > 0) request.setAttribute("sizeList", sizeList);
			
			
		} catch (Exception e) {
			throw new Exception(e.getMessage());
		}
		return mapping.findForward(forwardText);
	}
}