/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.dtac.inventory.action;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.LookupDispatchAction;

import com.dtac.admin.data.DBMasterTable;
import com.dtac.inventory.data.DBMaterial;
import com.dtac.inventory.data.DBMaterialType;
import com.dtac.inventory.form.MaterialForm;
/** 
 * MyEclipse Struts
 * Creation date: 22-04-2012
 */
public class MaterialSearchAction extends LookupDispatchAction {

	protected Map getKeyMethodMap() {
		Map map = new HashMap();		
		map.put("materialform.button.search",	"search");
		return map;
	}

	public ActionForward search(ActionMapping mapping, ActionForm form,
		HttpServletRequest request, HttpServletResponse response)
	throws Exception { //22-04-2012
		String forwardText = "success";
		String loginId 		= "";
		//String appCode  	= "sa11";
		try {
			HttpSession session = request.getSession();
			if (session.isNew()) {
				session.invalidate();
				request.setAttribute("alertMessage","Session Timeout. Login again.");
				return mapping.findForward("relogin");
			} else {
				loginId = (String) session.getAttribute("loginId");
				if (loginId == null) {
					request.setAttribute("alertMessage","Please Login.");
					return mapping.findForward("relogin");
				}
			}
			/*DBLogin dbLogin = new DBLogin();			
			if (!dbLogin.CheckAppAuth(loginId, appCode, "disp")) {
				request.setAttribute("alertMessage","You don't have authorize.");
				return mapping.findForward("alertmsg");
			}*/

			MaterialForm materialForm = (MaterialForm) form;
			String matCode		= materialForm.getMatCode();
			String matName		= new String(materialForm.getMatName().getBytes("ISO8859_1"),"utf-8");
			String serial		= materialForm.getMatSearchName(); if (serial == null) serial = "";
			String matSearchName= "";
			String matTypeCode	= "";
			String matGrpCode	= "";
			String matColorCode = "";
			String matBrandCode = "";
			String matStuffCode	= "";
			String refMatCode	= "";
			//String refMatName	= materialForm.getRefMatName();
			String matStatus	= "";
			String pUnit		= "";
			
			DBMaterialType dbMaterialType = new DBMaterialType();
			List matTypeList = dbMaterialType.GetMaterialTypeList("");
			if (matTypeList.size() > 0) request.setAttribute("matTypeList", matTypeList);

			List matGrpList = dbMaterialType.GetMaterialGrpList(matTypeCode, matGrpCode, "AC");
			if (matGrpList.size() > 0 && !matTypeCode.equals("")) request.setAttribute("matGrpList", matGrpList);

			DBMaterial dbMaterial = new DBMaterial();
			List materialList = dbMaterial.GetMaterialList(matCode, matName,serial, matSearchName, matTypeCode, matGrpCode, 
				matColorCode, matStuffCode, refMatCode, matStatus, pUnit, matBrandCode);
			if (materialList.size() > 0) request.setAttribute("materialList", materialList);
						
			DBMasterTable dbMasterTable = new DBMasterTable();
			List colorList = dbMasterTable.GetMasterTableDTList("colo", "", "", "AC");
			if (colorList.size() > 0) request.setAttribute("colorList", colorList);
			
			List unitList = dbMasterTable.GetMasterTableDTList("unit", "", "", "AC");
			if (unitList.size() > 0) request.setAttribute("unitList", unitList);
			
			List brandList = dbMasterTable.GetMasterTableDTList("bran", "", "", "AC");
			if (brandList.size() > 0) request.setAttribute("brandList", brandList);

			List stuffList = dbMasterTable.GetMasterTableDTList("stuf", "", "", "AC");
			if (stuffList.size() > 0) request.setAttribute("stuffList", stuffList);
			
			List sizeList = dbMasterTable.GetMasterTableDTList("size", "", "", "AC");
			if (sizeList.size() > 0) request.setAttribute("sizeList", sizeList);
			   
			materialForm.setMatName(matName);
			
		} catch (Exception e) {
			throw new Exception(e.getMessage());
		}
		return  mapping.findForward(forwardText);
	}
}