/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.dtac.inventory.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.dtac.inventory.data.DBMemberSearch;
import com.dtac.inventory.form.MemberSearchForm; 
import com.dtac.utils.DateUtil;
/** 
 * MyEclipse Struts
 * Creation date: 10-10-2007
 */
public class MemberSearchStartAction extends Action {

	public ActionForward execute(ActionMapping mapping, ActionForm form,
		HttpServletRequest request, HttpServletResponse response) 
	throws Exception {
		
		String forwardText 	= "success";
		String loginId 		= "";
		HttpSession session = request.getSession();
		if (session.isNew()) {
			session.invalidate();
			request.setAttribute("alertMessage","Session Timeout. Login again.");
			return mapping.findForward("relogin");
		} else {
			loginId = (String) session.getAttribute("loginId");
			request.setAttribute("loginId",loginId);
			String qty ="1";
			request.setAttribute("qty",qty);
			if (loginId == null) {
				request.setAttribute("alertMessage","Please Login.");
				return mapping.findForward("relogin");
			}
		}
		DateUtil dateUtil = new DateUtil();
		String date	= dateUtil.CnvToYYYYMMDD(dateUtil.curDate(), '-'); //2000-11-01
		String docDate	= dateUtil.CnvToDDMMYYYYThaiYear(date); //01/11/2557
		
		MemberSearchForm memberSearchForm = (MemberSearchForm) form;
		String requestNo = "";
		String docTypeCode = "SEL";
		String docyear 	= docDate.substring(6); // 2557
		String semesterNo = "";
		
		DBMemberSearch dbMemberSearch = new DBMemberSearch();
		requestNo = dbMemberSearch.SelectRequestnoView(requestNo, docTypeCode, docyear);
		//semesterNo = dbMemberSearch.SelectSemesterNo();
		
		memberSearchForm.setRequestNo(requestNo);
		//memberSearchForm.setSemesterNo(semesterNo);
		//request.setAttribute("semesterNo",	semesterNo);
		
		return  mapping.findForward(forwardText);
	}
}