/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.dtac.center.form;
import org.apache.struts.action.ActionForm;
/** 
 * MyEclipse Struts
 * Creation date: 09-04-2012
 */
public class AddressForm extends ActionForm {

	private static final long serialVersionUID = 1L;
	
	private String tableName;
	private String idCode;
	private String addrType;
	private String addrNo;
		
    private String addr1;
	private String addr2;
	private String addr3;
	private String cont1;
	private String posi1;
	private String tel1;
	private String mob1;
	private String fax1;
	private String email1;
	
	private String cont2;
	private String posi2;
	private String tel2;
	private String mob2;
	private String fax2;
	private String email2;

	private String remark;
	private String status;
	private String pic1;
	private String qty;
	
	public AddressForm() {}	
	public AddressForm(String tableName, String idCode, String addrType,
		String addrNo, String addr1, String addr2, String addr3,
		String cont1, String posi1, String tel1, String mob1, String fax1, String email1, 
		String cont2, String posi2, String tel2, String mob2, String fax2, String email2, 
		String remark, String status, String pic1, String qty) { //11-05-2012
		super();
		this.tableName = tableName;
		this.idCode = idCode;
		this.addrType = addrType;
		this.addrNo = addrNo;
		this.addr1 = addr1;
		this.addr2 = addr2;
		this.addr3 = addr3;
		this.cont1 = cont1;
		this.posi1 = posi1;
		this.tel1 = tel1;
		this.mob1 = mob1;
		this.fax1 = fax1;
		this.email1 = email1;
		this.cont2 = cont2;
		this.posi2 = posi2;
		this.tel2 = tel2;
		this.mob2 = mob2;
		this.fax2 = fax2;
		this.email2 = email2;
		this.remark = remark;
		this.status = status;
		this.pic1 = pic1;
		this.qty = qty;
	}
	public void initial() {
		this.tableName 	= "";
		this.idCode		= "";
		this.addrType 	= "";
		this.addrNo 	= "";
		this.addr1		= "";		
	}
	public String getTableName() {
		return tableName;
	}
	public void setTableName(String tableName) {
		this.tableName = tableName;
	}
	public String getIdCode() {
		return idCode;
	}
	public void setIdCode(String idCode) {
		this.idCode = idCode;
	}
	public String getAddrType() {
		return addrType;
	}
	public void setAddrType(String addrType) {
		this.addrType = addrType;
	}
	public String getAddrNo() {
		return addrNo;
	}
	public void setAddrNo(String addrNo) {
		this.addrNo = addrNo;
	}
	public String getAddr1() {
		return addr1;
	}
	public void setAddr1(String addr1) {
		this.addr1 = addr1;
	}
	public String getAddr2() {
		return addr2;
	}
	public void setAddr2(String addr2) {
		this.addr2 = addr2;
	}
	public String getAddr3() {
		return addr3;
	}
	public void setAddr3(String addr3) {
		this.addr3 = addr3;
	}
	public String getCont1() {
		return cont1;
	}
	public void setCont1(String cont1) {
		this.cont1 = cont1;
	}
	public String getTel1() {
		return tel1;
	}
	public void setTel1(String tel1) {
		this.tel1 = tel1;
	}
	public String getRemark() {
		return remark;
	}
	public void setRemark(String remark) {
		this.remark = remark;
	}
	public String getStatus() {
		return status;
	}
	public void setStatus(String status) {
		this.status = status;
	}
	public String getQty() {
		return qty;
	}
	public void setQty(String qty) {
		this.qty = qty;
	}
	public String getPosi1() {
		return posi1;
	}
	public void setPosi1(String posi1) {
		this.posi1 = posi1;
	}
	public String getMob1() {
		return mob1;
	}
	public void setMob1(String mob1) {
		this.mob1 = mob1;
	}
	public String getFax1() {
		return fax1;
	}
	public void setFax1(String fax1) {
		this.fax1 = fax1;
	}
	public String getEmail1() {
		return email1;
	}
	public void setEmail1(String email1) {
		this.email1 = email1;
	}
	public String getCont2() {
		return cont2;
	}
	public void setCont2(String cont2) {
		this.cont2 = cont2;
	}
	public String getPosi2() {
		return posi2;
	}
	public void setPosi2(String posi2) {
		this.posi2 = posi2;
	}
	public String getTel2() {
		return tel2;
	}
	public void setTel2(String tel2) {
		this.tel2 = tel2;
	}
	public String getMob2() {
		return mob2;
	}
	public void setMob2(String mob2) {
		this.mob2 = mob2;
	}
	public String getFax2() {
		return fax2;
	}
	public void setFax2(String fax2) {
		this.fax2 = fax2;
	}
	public String getEmail2() {
		return email2;
	}
	public void setEmail2(String email2) {
		this.email2 = email2;
	}
	public String getPic1() {
		return pic1;
	}
	public void setPic1(String pic1) {
		this.pic1 = pic1;
	}
}