/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.dtac.center.form;
import org.apache.struts.action.ActionForm;
/** 
 * MyEclipse Struts
 * Creation date: 19-04-2012
 */
public class ContactForm extends ActionForm { //not use

	private static final long serialVersionUID = 1L;
	
	private String tableName;
	private String idCode;
	private String contactNo;
	
	private String name;
	private String tel1;
	private String tel2;
	private String email;
	private String facebook;
	private String remark;
	
	public ContactForm() {}
	public ContactForm(String tableName, String idCode, String contactNo,
		String name, String tel1, String tel2, String email, String facebook, String remark) { //20-04-2012
		super();
		this.tableName = tableName;
		this.idCode = idCode;
		this.contactNo = contactNo;
		this.name = name;
		this.tel1 = tel1;
		this.tel2 = tel2;
		this.email = email;
		this.facebook = facebook;
		this.remark = remark;
	}

	public void reset() {		
		name ="";
	}
	public String getTableName() {
		return tableName;
	}
	public void setTableName(String tableName) {
		this.tableName = tableName;
	}
	public String getIdCode() {
		return idCode;
	}
	public void setIdCode(String idCode) {
		this.idCode = idCode;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getTel1() {
		return tel1;
	}
	public void setTel1(String tel1) {
		this.tel1 = tel1;
	}
	public String getTel2() {
		return tel2;
	}
	public void setTel2(String tel2) {
		this.tel2 = tel2;
	}
	public String getEmail() {
		return email;
	}
	public void setEmail(String email) {
		this.email = email;
	}
	public String getFacebook() {
		return facebook;
	}
	public void setFacebook(String facebook) {
		this.facebook = facebook;
	}
	public String getRemark() {
		return remark;
	}
	public void setRemark(String remark) {
		this.remark = remark;
	}
	public String getContactNo() {
		return contactNo;
	}
	public void setContactNo(String contactNo) {
		this.contactNo = contactNo;
	}
}