/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.dtac.employee.action;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.dtac.admin.data.DBLogin;
import com.dtac.admin.data.DBMasterTable;
import com.dtac.admin.data.DBMemberType;
import com.dtac.employee.data.DBEmployee;
import com.dtac.employee.form.EmployeeForm;
/** 
 * MyEclipse Struts
 * Creation date: 07-05-2012
 */
public class EmployeeListStartAction extends Action {

	public ActionForward execute(ActionMapping mapping, ActionForm form,
		HttpServletRequest request, HttpServletResponse response) 
	throws Exception { //20-01-2012
		String forwardText  = "success";
		String loginId 		= "";
		String appCode  	= "hr21";
		try {
			HttpSession session = request.getSession();
			if (session.isNew()) {
				session.invalidate();
				request.setAttribute("alertMessage","Session Timeout. Login again.");
				return mapping.findForward("relogin");
			} else {
				loginId = (String) session.getAttribute("loginId");
				if (loginId == null) {
					request.setAttribute("alertMessage","Please Login.");
					return mapping.findForward("relogin");
				}
			}
			DBLogin dbLogin = new DBLogin();			
			if (!dbLogin.CheckAppAuth(loginId,appCode,"disp")) {
				request.setAttribute("alertMessage","You don't have authorize.");
				return mapping.findForward("alertmsg");
			}
			
			EmployeeForm employeeForm = (EmployeeForm) form;
			employeeForm.initial();
			
			String empTypeCode = "ST";
			String empDeptCode = "";
			String offiCode		= "BR";
			if (session.getAttribute("empTypeCode") != null) empTypeCode = (String) session.getAttribute("empTypeCode");
			if (session.getAttribute("empDeptCode") != null) empDeptCode = (String) session.getAttribute("empDeptCode");
			if (session.getAttribute("offiCode") != null) 	 offiCode = (String) session.getAttribute("offiCode");
			
			DBEmployee dbEmployee = new DBEmployee();
			List employeeList = dbEmployee.GetEmployeeList("", "", "", empTypeCode, empDeptCode, offiCode, "AC");
			if (employeeList.size() > 0) request.setAttribute("employeeList", employeeList);

			DBMemberType dbMemberType = new DBMemberType();
			List memberTypeList = dbMemberType.GetMemberTypeList("", "", "");
			if (memberTypeList.size() > 0) request.setAttribute("memberTypeList", memberTypeList);

			DBMasterTable dbMasterTable = new DBMasterTable();
			List deptList = dbMasterTable.GetMasterTableDTList("dept", "", "", "AC");
			if (deptList.size() > 0) request.setAttribute("deptList", deptList);

			List offiList = dbMasterTable.GetMasterTableDTList("offi", "", "", "AC");
			if (offiList.size() > 0) request.setAttribute("offiList", offiList);

			employeeForm.setEmpTypeCode(empTypeCode);
			employeeForm.setEmpDeptCode(empDeptCode);
			employeeForm.setOffiCode(offiCode);
			employeeForm.setStatus("AC");
		} catch (Exception e) {
			throw new Exception(e.getMessage());
		}	
		return mapping.findForward(forwardText);
	}
}