/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.dtac.employee.action;
import java.util.HashMap;

import java.util.Map;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.LookupDispatchAction;

import com.dtac.admin.data.DBLogin;
import com.dtac.employee.form.EmployeeForm;
/** 
 * MyEclipse Struts
 * Creation date: 23-08-2012
 */
public class EmployeeReport1Action extends LookupDispatchAction {

	protected Map getKeyMethodMap() {
		Map map = new HashMap();
		map.put("employeeform.button.print",	"print");
		map.put("employeeform.button.excel",	"excel");	 
		return map;
	}

	public ActionForward print(ActionMapping mapping, ActionForm form,
		HttpServletRequest request, HttpServletResponse response)
	throws Exception { //03-01-2012
		String forwardText 	= "print";
		String loginId 		= "";
		String appCode  	= "hrr1";
		try {
			HttpSession session = request.getSession();
			if (session.isNew()) {
				session.invalidate();
				request.setAttribute("alertMessage","Session Timeout. Login again.");
				return mapping.findForward("relogin");
			} else {
				loginId = (String) session.getAttribute("loginId");
				if (loginId == null) {
					request.setAttribute("alertMessage","Please Login.");
					return mapping.findForward("relogin");
				}
			}
			DBLogin dbLogin = new DBLogin();			
			if (!dbLogin.CheckAppAuth(loginId, appCode, "disp")) {
				request.setAttribute("alertMessage","You don't have authorize.");
				return mapping.findForward("alertmsg");
			}

			EmployeeForm employeeForm = (EmployeeForm) form;
			String empTypeCode	= employeeForm.getEmpTypeCode();
			String groupName 	= new String (employeeForm.getGroupName().getBytes("ISO8859_1"),"utf-8");
			String reportNo		= employeeForm.getReportNo();

			request.setAttribute("reportNo", reportNo);
			request.setAttribute("groupName", groupName);
			request.setAttribute("empTypeCode", empTypeCode);
			
			session.setAttribute("empTypeCode", empTypeCode);
			session.setAttribute("groupName", groupName);
		} catch (Exception e) {
			throw new Exception(e.getMessage());
		}
		return  mapping.findForward(forwardText);
	}
}