/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.dtac.employee.action;
import java.util.HashMap;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.LookupDispatchAction;

import com.dtac.admin.data.DBLogin;
import com.dtac.employee.form.TimeAttendForm;
import com.dtac.utils.DateUtil;
/** 
 * MyEclipse Struts
 * Creation date: 23-08-2012
 */
public class TimeAttendReport1Action extends LookupDispatchAction {

	protected Map getKeyMethodMap() {
		Map map = new HashMap();
		map.put("timeattendform.button.print",	"print");
		map.put("timeattendform.button.excel",	"excel");	 
		return map;
	}

	public ActionForward print(ActionMapping mapping, ActionForm form,
		HttpServletRequest request, HttpServletResponse response)
	throws Exception { //13-08-2012
		String forwardText 	= "print";
		String loginId 		= "";
		String appCode  	= "hrr2";
		try {
			HttpSession session = request.getSession();
			if (session.isNew()) {
				session.invalidate();
				request.setAttribute("alertMessage","Session Timeout. Login again.");
				return mapping.findForward("relogin");
			} else {
				loginId = (String) session.getAttribute("loginId");
				if (loginId == null) {
					request.setAttribute("alertMessage","Please Login.");
					return mapping.findForward("relogin");
				}
			}
			DBLogin dbLogin = new DBLogin();			
			if (!dbLogin.CheckAppAuth(loginId, appCode, "disp")) {
				request.setAttribute("alertMessage","You don't have authorize.");
				return mapping.findForward("alertmsg");
			}

			TimeAttendForm timeAttendForm = (TimeAttendForm) form;
			String empID		= timeAttendForm.getEmpID(); 
			String empTypeCode	= timeAttendForm.getEmpTypeCode();
			String empDeptCode	= timeAttendForm.getEmpDeptCode();
			String groupName 	= new String (timeAttendForm.getGroupName().getBytes("ISO8859_1"),"utf-8");
			String fromDate		= timeAttendForm.getFromDate();
			String toDate		= timeAttendForm.getToDate();
			String year			= timeAttendForm.getYear();
			String month		= timeAttendForm.getMonth();
			String reportNo		= timeAttendForm.getReportNo();
			String alertMessage = "";
			String strDate		= "";
			
			DateUtil dateUtil = new DateUtil();
			if (fromDate.trim().length() != 10) alertMessage = "check From Date";
			else if (!dateUtil.isValidDateStr(dateUtil.CnvToYYYYMMDDEngYear(fromDate, '-'))) alertMessage = "check From Date";
			
			else if (toDate.trim().length() != 10) alertMessage = "check To Date";
			else if (!dateUtil.isValidDateStr(dateUtil.CnvToYYYYMMDDEngYear(toDate, '-'))) alertMessage = "check To Date";
			
			if (!alertMessage.equals("")) {
				forwardText = "repeat";
				request.setAttribute("alertMessage", alertMessage);
			} else {
				request.setAttribute("empID", empID);
				request.setAttribute("empTypeCode", empTypeCode);
				request.setAttribute("empDeptCode", empDeptCode);
				request.setAttribute("groupName", groupName);
				request.setAttribute("fromDate", dateUtil.CnvToYYYYMMDDEngYear(fromDate, '-'));
				request.setAttribute("toDate", dateUtil.CnvToYYYYMMDDEngYear(toDate, '-'));
				request.setAttribute("year", year);
				request.setAttribute("month", month);
				request.setAttribute("reportNo", reportNo);
				
				strDate = dateUtil.CnvToDDMMYYYYThaiYear(dateUtil.CnvToYYYYMMDDEngYear(fromDate, '-'));				
				if (reportNo.equals("2") || reportNo.equals("3")) 
					strDate = strDate + " - " + dateUtil.CnvToDDMMYYYYThaiYear(dateUtil.CnvToYYYYMMDDEngYear(toDate, '-'));
				
				request.setAttribute("strDate", strDate);
				
				session.setAttribute("empTypeCode", empTypeCode);
				session.setAttribute("empDeptCode", empDeptCode);
				session.setAttribute("groupName", groupName);
				session.setAttribute("fromDate", fromDate);
				session.setAttribute("toDate", toDate);
				session.setAttribute("year", year);
				session.setAttribute("month", month);
			}
			
		} catch (Exception e) {
			throw new Exception(e.getMessage());
		}
		return  mapping.findForward(forwardText);
	}
}