/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.dtac.employee.action;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.dtac.admin.data.DBLogin;
import com.dtac.admin.data.DBMemberType;
import com.dtac.employee.data.DBEmployee;
import com.dtac.employee.form.WorkTimeForm;
import com.dtac.utils.DateUtil;
/** 
 * MyEclipse Struts
 * Creation date: 20-08-2012 
 */
public class WorkTimeListStartAction extends Action {

	public ActionForward execute(ActionMapping mapping, ActionForm form,
		HttpServletRequest request, HttpServletResponse response) 
	throws Exception { //06-10-2011
		String forwardText  = "success";
		String loginId 		= "";
		String appCode  	= "hr42";
		try {
			HttpSession session = request.getSession();
			if (session.isNew()) {
				session.invalidate();
				request.setAttribute("alertMessage","Session Timeout. Login again.");
				return mapping.findForward("relogin");
			} else {
				loginId = (String) session.getAttribute("loginId");
				if (loginId == null) {
					request.setAttribute("alertMessage","Please Login.");
					return mapping.findForward("relogin");
				}
			}
			DBLogin dbLogin = new DBLogin();			
			if (!dbLogin.CheckAppAuth(loginId,appCode,"disp")) {
				request.setAttribute("alertMessage","You don't have authorize.");
				return mapping.findForward("alertmsg");
			}
			
			WorkTimeForm workTimeForm = (WorkTimeForm) form;
			workTimeForm.initial();
			
			String empTypeCode = "ST";
			String empDeptCode = "";
			String docTypeCode = "";
			if (session.getAttribute("empTypeCode") != null) empTypeCode = (String) session.getAttribute("empTypeCode");
			if (session.getAttribute("empDeptCode") != null) empDeptCode = (String) session.getAttribute("empDeptCode");
			
			DateUtil dateUtil = new DateUtil();
			String workDate = dateUtil.CnvToDDMMYYYYThaiYear(dateUtil.subtractDate(dateUtil.CnvToYYYYMMDD(dateUtil.curDate(), '/'), 1));
			
			if (session.getAttribute("workDate") != null) workDate = (String) session.getAttribute("workDate");
 
			DBMemberType dbMemberType = new DBMemberType();
			List memberTypeList = dbMemberType.GetMemberTypeList("", "", "");
			if (memberTypeList.size() > 0) request.setAttribute("memberTypeList", memberTypeList);

			DBEmployee dbEmployee = new DBEmployee();
			List employeeList = dbEmployee.GetEmployeeList("", "", "", empTypeCode, empDeptCode, "", "AC");
			if (employeeList.size() > 0) request.setAttribute("employeeList", employeeList);

			workTimeForm.setEmpTypeCode(empTypeCode);
			workTimeForm.setEmpDeptCode(empDeptCode);
			workTimeForm.setWorkDate(workDate);
			workTimeForm.setWorkStatus("AC");
		} catch (Exception e) {
			throw new Exception(e.getMessage());
		}	
		return mapping.findForward(forwardText);
	}
}