/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.dtac.admin.action;
import java.util.HashMap;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.LookupDispatchAction;

import com.dtac.admin.data.DBLogin;
import com.dtac.admin.form.MemberAuthForm;
import com.dtac.utils.DateUtil;
/**
 * MyEclipse Struts 
 * Creation date: 12-12-2012
 */
public class LoginReport1Action extends LookupDispatchAction {

	protected Map getKeyMethodMap() {
		Map map = new HashMap();
		map.put("memberform.button.print", "print");
		return map;
	}

	public ActionForward print(ActionMapping mapping, ActionForm form,
		HttpServletRequest request, HttpServletResponse response)
	throws Exception { // 13-12-2012
		String forwardText 	= "print";
		String loginId 		= "";
		String appCode 		= "ad13";
		try {
			HttpSession session = request.getSession();
			if (session.isNew()) {
				session.invalidate();
				request.setAttribute("alertMessage", "Session Timeout. Login again.");
				return mapping.findForward("relogin");
			} else {
				loginId = (String) session.getAttribute("loginId");
				if (loginId == null) {
					request.setAttribute("alertMessage", "Please Login.");
					return mapping.findForward("relogin");
				}
			}
			DBLogin dbLogin = new DBLogin();
			if (!dbLogin.CheckAppAuth(loginId, appCode, "disp")) {
				request.setAttribute("alertMessage", "You don't have authorize.");
				return mapping.findForward("alertmsg");
			}

			MemberAuthForm memberAuthForm = (MemberAuthForm) form;
			String memberId 	= memberAuthForm.getMemberID();
			String fromDate		= memberAuthForm.getFromDate();
			String toDate		= memberAuthForm.getToDate();
			String reportNo 	= memberAuthForm.getReportNo();
			String alertMessage = "";
			String strDate		= "";

			DateUtil dateUtil = new DateUtil();
			if (fromDate.trim().length() != 10) alertMessage = "check From Date";
			else if (!dateUtil.isValidDateStr(dateUtil.CnvToYYYYMMDDEngYear(fromDate, '-'))) alertMessage = "check From Date";
			
			else if (toDate.trim().length() != 10) alertMessage = "check To Date";
			else if (!dateUtil.isValidDateStr(dateUtil.CnvToYYYYMMDDEngYear(toDate, '-'))) alertMessage = "check To Date";

			if (!alertMessage.equals("")) {
				forwardText = "repeat";
				request.setAttribute("alertMessage", alertMessage);
			} else {
				request.setAttribute("memberId", memberId);
				request.setAttribute("fromDate", dateUtil.CnvToYYYYMMDDEngYear(fromDate, '-'));
				request.setAttribute("toDate", dateUtil.CnvToYYYYMMDDEngYear(toDate, '-'));
				request.setAttribute("reportNo", reportNo);
				
				strDate = dateUtil.CnvToDDMMYYYYThaiYear(dateUtil.CnvToYYYYMMDDEngYear(fromDate, '-'));				
				if (reportNo.equals("1") || reportNo.equals("3")) 
					strDate = strDate + " - " + dateUtil.CnvToDDMMYYYYThaiYear(dateUtil.CnvToYYYYMMDDEngYear(toDate, '-'));
				
				request.setAttribute("strDate", strDate);
				
				session.setAttribute("fromDate", fromDate);
				session.setAttribute("toDate", toDate);
			}

		} catch (Exception e) {
			throw new Exception(e.getMessage());
		}
		return mapping.findForward(forwardText);
	}
}