/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.dtac.admin.action;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.dtac.admin.data.DBLogin;
import com.dtac.admin.data.DBMasterTable;
import com.dtac.admin.form.MasterTableForm;
/** 
 * MyEclipse Struts
 * Creation date: 12-04-2012
 */
public class MasterTableListStartAction extends Action {

	public ActionForward execute(ActionMapping mapping, ActionForm form,
		HttpServletRequest request, HttpServletResponse response) 
	throws Exception {	//30-09-2011
		String forwardText 	= "success";
		String loginId 		= "";
		String appCode  	= "";
		String applTypeCode = "mm";
		if (request.getParameter("applType") != null) applTypeCode  = request.getParameter("applType");
		appCode = applTypeCode+"00";
		
		try {
			HttpSession session = request.getSession();
			if (session.isNew()) {
				session.invalidate();
				request.setAttribute("alertMessage","Session Timeout. Login again.");
				return mapping.findForward("relogin");
			} else {
				loginId = (String) session.getAttribute("loginId");
				if (loginId == null) {
					request.setAttribute("alertMessage","Please Login.");
					return mapping.findForward("relogin");
				}
			}
			DBLogin dbLogin = new DBLogin();			
			if (!dbLogin.CheckAppAuth(loginId, appCode, "disp")) {
				request.setAttribute("alertMessage", "You don't have authorize.");
				return mapping.findForward("alertmsg");
			}

			MasterTableForm masterTableForm = (MasterTableForm) form;
			masterTableForm.initial();
									
			String grpCode 	= "dept";						
			if (request.getParameter("grpCode") != null) grpCode  = request.getParameter("grpCode");
			
			DBMasterTable dbMasterTable = new DBMasterTable();
			List grpList = dbMasterTable.GetMasterTableHDList(applTypeCode, "", "");			
			if (grpList.size() > 0) request.setAttribute("grpList", grpList);

			List typeList = dbMasterTable.GetMasterTableDTList(grpCode, "", "", "");
			if (typeList.size() > 0) request.setAttribute("typeList", typeList);

			masterTableForm.setApplTypeCode(applTypeCode);
			masterTableForm.setGrpCode(grpCode);
			request.setAttribute("grpCode", grpCode);
			
		} catch (Exception e) {
			throw new Exception(e.getMessage());
		}
		return  mapping.findForward(forwardText);
	}
}