/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.dtac.inventory.form;
import java.util.List;

import org.apache.struts.action.ActionForm;

import com.dtac.center.form.AddressForm;
/** 
 * MyEclipse Struts
 * Creation date: 09-04-2012
 */
public class CustomerForm extends ActionForm {

	private static final long serialVersionUID = 1L;
		
	private String customerCode;
	private	String customerName;
	private String customerTypeCode;
	private String customerTypeName;
	private String customerTaxId;
	private String searchName;
	private String creditLimit;
	private String creditAvail;
	
	private String status;
	private String updateByCode;
	private String updateByName;
	private String updateDate;
		
	
	private String regiAddr1;
	private String regiAddr2;
	private String regiAddr3;
		
	private String regiCont1;
	private String regiPosi1;
	private String regiTel1;
	private String regiMob1;
	private String regiFax1;
	private String regiEmail1;
	private String regiRemark;
	
	
	private String regiCont2;
	private String regiPosi2;
	private String regiTel2;
	private String regiMob2;
	private String regiFax2;
	private String regiEmail2;
	
	private String pic1;
	private String pic2;
	private String pic3;
	private String pic4;
	private String pic5;
	
	private String formName;
	
	public CustomerForm() {}
	public CustomerForm(String customerCode, String customerName, String searchName, 
		String customerTypeCode, String customerTypeName, 
		String customerTaxId, String creditLimit, String creditAvail, String status,
		String pic1, String pic2, String pic3, String pic4, String pic5) { //29-04-2012
		super();
		this.customerCode = customerCode;
		this.customerName = customerName;
		this.searchName = searchName;
		this.customerTypeCode = customerTypeCode;
		this.customerTypeName = customerTypeName;
		this.customerTaxId = customerTaxId;
		this.creditLimit = creditLimit;
		this.creditAvail = creditAvail;
		this.status 	= status;
		this.pic1		= pic1;
		this.pic2		= pic2;
		this.pic3		= pic3;
		this.pic4		= pic4;
		this.pic5		= pic5;		
	}
	public void set_regiAddress(List addrList) {
		AddressForm addrInfo = (AddressForm) addrList.get(0);
		this.regiAddr1 = addrInfo.getAddr1();
		this.regiAddr2 = addrInfo.getAddr2();
		this.regiAddr3 = addrInfo.getAddr3();
		this.regiCont1 = addrInfo.getCont1();
		this.regiPosi1 = addrInfo.getPosi1();
		this.regiTel1  = addrInfo.getTel1();
		this.regiMob1  = addrInfo.getMob1();
		this.regiFax1  = addrInfo.getFax1();
		this.regiEmail1 = addrInfo.getEmail1();	
		
		this.regiCont2 = addrInfo.getCont2();
		this.regiPosi2 = addrInfo.getPosi2();
		this.regiTel2  = addrInfo.getTel2();
		this.regiMob2  = addrInfo.getMob2();
		this.regiFax2  = addrInfo.getFax2();
		this.regiEmail2 = addrInfo.getEmail2();		
		this.regiRemark = addrInfo.getRemark();
		this.status		= addrInfo.getStatus();
	}	
	public void set_regiAddress(String regiAddr1, String regiAddr2, String regiAddr3, 
		String regiCont1, String regiPosi1, String regiTel1, String regiMob1, String regiFax1, String regiEmail1, 
		String regiCont2, String regiPosi2, String regiTel2, String regiMob2, String regiFax2, String regiEmail2, 
		String regiRemark) {
		this.regiAddr1 = regiAddr1;
		this.regiAddr2 = regiAddr2;
		this.regiAddr3 = regiAddr3;
		this.regiCont1 = regiCont1;
		this.regiPosi1 = regiPosi1;
		this.regiTel1 = regiTel1;
		this.regiMob1 = regiMob1;
		this.regiFax1 = regiFax1;
		this.regiEmail1 = regiEmail1;		
		this.regiCont2 = regiCont2;
		this.regiPosi2 = regiPosi2;
		this.regiTel2 = regiTel2;
		this.regiMob2 = regiMob2;
		this.regiFax2 = regiFax2;
		this.regiEmail2 = regiEmail2;		
		this.regiRemark = regiRemark;		
	}
	public void initial() {		
		customerCode 	= "";
		customerName	= "";
		searchName	= "";
		customerTypeCode= "";
		customerTypeName= "";
		customerTaxId	= "";
		creditLimit	= "";
		creditAvail	= "";
		status = "";
	}
	public void regi_initial() {		
		this.regiAddr1 = "";
		this.regiAddr2 = "";
		this.regiAddr3 = "";
		this.regiTel1 = "";
		this.regiRemark = "";
	}	
	public String getSearchName() {
		return searchName;
	}
	public void setSearchName(String searchName) {
		this.searchName = searchName;
	}
	public String getStatus() {
		return status;
	}
	public void setStatus(String status) {
		this.status = status;
	}
	public String getUpdateByCode() {
		return updateByCode;
	}
	public void setUpdateByCode(String updateByCode) {
		this.updateByCode = updateByCode;
	}
	public String getUpdateByName() {
		return updateByName;
	}
	public void setUpdateByName(String updateByName) {
		this.updateByName = updateByName;
	}
	public String getUpdateDate() {
		return updateDate;
	}
	public void setUpdateDate(String updateDate) {
		this.updateDate = updateDate;
	}
	public String getFormName() {
		return formName;
	}
	public void setFormName(String formName) {
		this.formName = formName;
	}	
	public String getRegiAddr1() {
		return regiAddr1;
	}
	public void setRegiAddr1(String regiAddr1) {
		this.regiAddr1 = regiAddr1;
	}
	public String getRegiAddr2() {
		return regiAddr2;
	}
	public void setRegiAddr2(String regiAddr2) {
		this.regiAddr2 = regiAddr2;
	}
	public String getRegiAddr3() {
		return regiAddr3;
	}
	public void setRegiAddr3(String regiAddr3) {
		this.regiAddr3 = regiAddr3;
	}
	public String getRegiCont1() {
		return regiCont1;
	}
	public void setRegiCont1(String regiCont1) {
		this.regiCont1 = regiCont1;
	}
	public String getRegiTel1() {
		return regiTel1;
	}
	public void setRegiTel1(String regiTel1) {
		this.regiTel1 = regiTel1;
	}
	public String getRegiRemark() {
		return regiRemark;
	}
	public void setRegiRemark(String regiRemark) {
		this.regiRemark = regiRemark;
	}
	public String getcustomerCode() {
		return customerCode;
	}
	public void setcustomerCode(String customerCode) {
		this.customerCode = customerCode;
	}
	public String getcustomerName() {
		return customerName;
	}
	public void setcustomerName(String customerName) {
		this.customerName = customerName;
	}
	public String getcustomerTypeCode() {
		return customerTypeCode;
	}
	public void setcustomerTypeCode(String customerTypeCode) {
		this.customerTypeCode = customerTypeCode;
	}
	public String getcustomerTypeName() {
		return customerTypeName;
	}
	public void setcustomerTypeName(String customerTypeName) {
		this.customerTypeName = customerTypeName;
	}
	public String getcustomerTaxId() {
		return customerTaxId;
	}
	public void setcustomerTaxId(String customerTaxId) {
		this.customerTaxId = customerTaxId;
	}
	public String getRegiPosi1() {
		return regiPosi1;
	}
	public void setRegiPosi1(String regiPosi1) {
		this.regiPosi1 = regiPosi1;
	}
	public String getRegiMob1() {
		return regiMob1;
	}
	public void setRegiMob1(String regiMob1) {
		this.regiMob1 = regiMob1;
	}
	public String getRegiFax1() {
		return regiFax1;
	}
	public void setRegiFax1(String regiFax1) {
		this.regiFax1 = regiFax1;
	}
	public String getRegiEmail1() {
		return regiEmail1;
	}
	public void setRegiEmail1(String regiEmail1) {
		this.regiEmail1 = regiEmail1;
	}
	public String getRegiCont2() {
		return regiCont2;
	}
	public void setRegiCont2(String regiCont2) {
		this.regiCont2 = regiCont2;
	}
	public String getRegiPosi2() {
		return regiPosi2;
	}
	public void setRegiPosi2(String regiPosi2) {
		this.regiPosi2 = regiPosi2;
	}
	public String getRegiTel2() {
		return regiTel2;
	}
	public void setRegiTel2(String regiTel2) {
		this.regiTel2 = regiTel2;
	}
	public String getRegiMob2() {
		return regiMob2;
	}
	public void setRegiMob2(String regiMob2) {
		this.regiMob2 = regiMob2;
	}
	public String getRegiFax2() {
		return regiFax2;
	}
	public void setRegiFax2(String regiFax2) {
		this.regiFax2 = regiFax2;
	}
	public String getRegiEmail2() {
		return regiEmail2;
	}
	public void setRegiEmail2(String regiEmail2) {
		this.regiEmail2 = regiEmail2;
	}
	public String getPic1() {
		return pic1;
	}
	public void setPic1(String pic1) {
		this.pic1 = pic1;
	}
	public String getPic2() {
		return pic2;
	}
	public void setPic2(String pic2) {
		this.pic2 = pic2;
	}
	public String getPic3() {
		return pic3;
	}
	public void setPic3(String pic3) {
		this.pic3 = pic3;
	}
	public String getPic4() {
		return pic4;
	}
	public void setPic4(String pic4) {
		this.pic4 = pic4;
	}
	public String getPic5() {
		return pic5;
	}
	public void setPic5(String pic5) {
		this.pic5 = pic5;
	}
	public String getCreditLimit() {
		return creditLimit;
	}
	public void setCreditLimit(String creditLimit) {
		this.creditLimit = creditLimit;
	}
	public String getCreditAvail() {
		return creditAvail;
	}
	public void setCreditAvail(String creditAvail) {
		this.creditAvail = creditAvail;
	}
}