/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.dtac.inventory.form;
import java.util.List;

import org.apache.struts.action.ActionForm;

import com.dtac.center.form.AddressForm;
/** 
 * MyEclipse Struts
 * Creation date: 09-04-2012
 */
public class ProductForm extends ActionForm {

	private static final long serialVersionUID = 1L;
		
	private String productCode;
	private	String productName;
 
	private String price;
 
	
	private String status;
	 
	
	public ProductForm() {}
	public ProductForm(String productCode, String productName, String price,String status) { //29-04-2012
		super();
		this.productCode = productCode;
		this.productName = productName;
		this.price = price;
		
		this.status 	= status;
	 	
	}
	 
	public void initial() {		
		productCode 	= "";
		productName	= "";
		price	= "";
		 
		status = "";
	}
	public String getProductCode() {
		return productCode;
	}
	public void setProductCode(String productCode) {
		this.productCode = productCode;
	}
	public String getProductName() {
		return productName;
	}
	public void setProductName(String productName) {
		this.productName = productName;
	}
	public String getPrice() {
		return price;
	}
	public void setPrice(String price) {
		this.price = price;
	}
	public String getStatus() {
		return status;
	}
	public void setStatus(String status) {
		this.status = status;
	}
 
}