/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.dtac.employee.form;

import org.apache.struts.action.ActionForm;
/** 
 * MyEclipse Struts
 * Creation date: 09-13-2011
 */
public class EmployeeForm extends ActionForm {

	private static final long serialVersionUID = 1L;
	private String empID;
	private String oldEmpID;
	private String empNameT;
	private String empLastNameT;
	private String empNameE;
	private String empLastNameE;
	private String empTypeCode;
	private String empTypeName;
	private String empDeptCode;
	private String empDeptName;
	private String offiCode;
	private String offiName;
	
	private String address1;
	private String address2;
	private String tel1;
	private String email1;

	private String nation;
	private String sex;
	private String marryStatus;
	private String allChild;
	private String edcChild;
	private String deductType;
	
	private String accountNo;
	private String taxID;
	private String idPop;
	private String socialNo;
	private String insure;
	private String devote;
	private String interestLoan;
	
	private String birthDay;
	private String workDate;
	private String expDate;
	private String educCode;
	private String major;
	//private String proVidenDate;	
	private String groupName;
	private String projCode;
	private String subProjCode;
	private String pfundDate;	
	private String pfFlag;	
	private String punchCard;
	private String status;
	private String reportNo;
	private String formName;
	
	public EmployeeForm() {}
	public EmployeeForm(String empID, String oldEmpID, String empNameT, String empLastNameT,
		String empNameE, String empLastNameE, 
		String empTypeCode, String empTypeName, String empDeptCode, String empDeptName, String offiCode, String offiName,
		String address1, String address2, String tel1, String email1, String nation, String sex, 
		String marryStatus,	String allChild, String edcChild, String deductType,
		String birthDay, String workDate ,String expDate, String educCode, String major,
		String groupName, String projCode, String subProjCode, String pfundDate, String pfFlag, String punchCard,
		String status,
		String accountNo, String taxID,	String idPop, String socialNo, String insure,
		String devote, String interestLoan) { //10-02-2013
		super();
		this.empID = empID;
		this.oldEmpID = oldEmpID;
		this.empNameT = empNameT;
		this.empLastNameT = empLastNameT;
		this.empNameE = empNameE;
		this.empLastNameE = empLastNameE;
		this.empTypeCode = empTypeCode;
		this.empTypeName = empTypeName;
		this.empDeptCode = empDeptCode;
		this.empDeptName = empDeptName;	
		this.offiCode = offiCode; 
		this.offiName = offiName;
		this.address1 = address1;
		this.address2 = address2;
		this.tel1 	= tel1;
		this.email1 = email1;
		this.nation = nation;
		this.sex 	= sex;
		this.marryStatus = marryStatus;
		this.allChild = allChild;
		this.edcChild = edcChild;
		this.deductType = deductType;
		this.birthDay = birthDay;
		this.workDate = workDate;
		this.expDate = expDate;
		this.educCode = educCode;
		this.major = major;
		this.groupName = groupName;
		this.projCode = projCode;
		this.subProjCode = subProjCode;
		this.pfundDate = pfundDate;
		this.pfFlag = pfFlag;
		this.punchCard = punchCard;
		this.status = status;		
		this.accountNo = accountNo;
		this.taxID = taxID;
		this.idPop = idPop;
		this.socialNo = socialNo;
		this.insure = insure;
		this.devote = devote;
		this.interestLoan=interestLoan;
	}
	public void initial() {
		
		empID ="";
		nation="";
		address1="";
		address2="";
		sex="";
		birthDay ="";
		
		accountNo ="";
		idPop ="";
		taxID = "";
		socialNo="";
		insure ="";
		devote="";
		interestLoan="";
		allChild="";
	    edcChild="";
	    workDate="";
	    
	    empNameT="";
	    empLastNameT="";
	    expDate="";
	    status ="";
	    groupName ="";
	    projCode = "";
	    subProjCode = "";
	    pfundDate ="";
	    major ="";
	    empNameE="";
	    empLastNameE="";
	}
	public String getEmpID() {
		return empID;
	}
	public void setEmpID(String empID) {
		this.empID = empID;
	}
	public String getBirthDay() {
		return birthDay;
	}
	public void setBirthDay(String birthDay) {
		this.birthDay = birthDay;
	}
	public String getEmpNameT() {
		return empNameT;
	}
	public void setEmpNameT(String empNameT) {
		this.empNameT = empNameT;
	}
	public String getEmpNameE() {
		return empNameE;
	}
	public void setEmpNameE(String empNameE) {
		this.empNameE = empNameE;
	}
	public String getEmpLastNameT() {
		return empLastNameT;
	}
	public void setEmpLastNameT(String empLastNameT) {
		this.empLastNameT = empLastNameT;
	}
	public String getEmpLastNameE() {
		return empLastNameE;
	}
	public void setEmpLastNameE(String empLastNameE) {
		this.empLastNameE = empLastNameE;
	}
	public String getEmpTypeCode() {
		return empTypeCode;
	}
	public void setEmpTypeCode(String empTypeCode) {
		this.empTypeCode = empTypeCode;
	}
	public String getEmpTypeName() {
		return empTypeName;
	}
	public void setEmpTypeName(String empTypeName) {
		this.empTypeName = empTypeName;
	}
	public String getStatus() {
		return status;
	}
	public void setStatus(String status) {
		this.status = status;
	}
	public String getEmpDeptCode() {
		return empDeptCode;
	}
	public void setEmpDeptCode(String empDeptCode) {
		this.empDeptCode = empDeptCode;
	}
	public String getEmpDeptName() {
		return empDeptName;
	}
	public void setEmpDeptName(String empDeptName) {
		this.empDeptName = empDeptName;
	}
	public String getReportNo() {
		return reportNo;
	}
	public final String getPfFlag() {
		return pfFlag;
	}
	public final void setPfFlag(String pfFlag) {
		this.pfFlag = pfFlag;
	}
	public final String getMajor() {
		return major;
	}
	public final void setMajor(String major) {
		this.major = major;
	}
	public final String getPfundDate() {
		return pfundDate;
	}
	public final void setPfundDate(String pfundDate) {
		this.pfundDate = pfundDate;
	}
	public final String getMarryStatus() {
		return marryStatus;
	}
	public final void setMarryStatus(String marryStatus) {
		this.marryStatus = marryStatus;
	}
	public final String getGroupName() {
		return groupName;
	}
	public final void setGroupName(String groupName) {
		this.groupName = groupName;
	}
	public String getExpDate() {
		return expDate;
	}
	public void setExpDate(String expDate) {
		this.expDate = expDate;
	}
	public String getAllChild() {
		return allChild;
	}
	public void setAllChild(String allChild) {
		this.allChild = allChild;
	}
	public String getEdcChild() {
		return edcChild;
	}
	public void setEdcChild(String edcChild) {
		this.edcChild = edcChild;
	}
	public String getWorkDate() {
		return workDate;
	}
	public void setWorkDate(String workDate) {
		this.workDate = workDate;
	}
	public String getInsure() {
		return insure;
	}
	public void setInsure(String insure) {
		this.insure = insure;
	}
	public String getDevote() {
		return devote;
	}
	public void setDevote(String devote) {
		this.devote = devote;
	}
	public String getInterestLoan() {
		return interestLoan;
	}
	public void setInterestLoan(String interestLoan) {
		this.interestLoan = interestLoan;
	}
	public String getAccountNo() {
		return accountNo;
	}
	public void setAccountNo(String accountNo) {
		this.accountNo = accountNo;
	}
	public String getTaxID() {
		return taxID;
	}
	public void setTaxID(String taxID) {
		this.taxID = taxID;
	}
	public String getIdPop() {
		return idPop;
	}
	public void setIdPop(String idPop) {
		this.idPop = idPop;
	}
	public String getSocialNo() {
		return socialNo;
	}
	public void setSocialNo(String socialNo) {
		this.socialNo = socialNo;
	}
	public String getSex() {
		return sex;
	}
	public void setSex(String sex) {
		this.sex = sex;
	}
	public String getAddress1() {
		return address1;
	}
	public void setAddress1(String address1) {
		this.address1 = address1;
	}
	public String getAddress2() {
		return address2;
	}
	public void setAddress2(String address2) {
		this.address2 = address2;
	}
	public String getNation() {
		return nation;
	}
	public void setNation(String nation) {
		this.nation = nation;
	}
	public void setReportNo(String reportNo) {
		this.reportNo = reportNo;
	}
	public String getEducCode() {
		return educCode;
	}
	public void setEducCode(String educCode) {
		this.educCode = educCode;
	}
	public String getOldEmpID() {
		return oldEmpID;
	}
	public void setOldEmpID(String oldEmpID) {
		this.oldEmpID = oldEmpID;
	}
	public String getDeductType() {
		return deductType;
	}
	public void setDeductType(String deductType) {
		this.deductType = deductType;
	}
	public String getProjCode() {
		return projCode;
	}
	public void setProjCode(String projCode) {
		this.projCode = projCode;
	}
	public String getSubProjCode() {
		return subProjCode;
	}
	public void setSubProjCode(String subProjCode) {
		this.subProjCode = subProjCode;
	}
	public String getPunchCard() {
		return punchCard;
	}
	public void setPunchCard(String punchCard) {
		this.punchCard = punchCard;
	}
	public String getFormName() {
		return formName;
	}
	public void setFormName(String formName) {
		this.formName = formName;
	}
	public String getOffiCode() {
		return offiCode;
	}
	public void setOffiCode(String offiCode) {
		this.offiCode = offiCode;
	}
	public String getOffiName() {
		return offiName;
	}
	public void setOffiName(String offiName) {
		this.offiName = offiName;
	}
	public String getTel1() {
		return tel1;
	}
	public void setTel1(String tel1) {
		this.tel1 = tel1;
	}
	public String getEmail1() {
		return email1;
	}
	public void setEmail1(String email1) {
		this.email1 = email1;
	}
}